:sparkles: Add HealtComponent with damage and death; Add reset and start game functions
avans-night-byte/game pull request #17
Opened 2020-12-07 15:16 UTC by marc0tjevp

2020-12-07 15:19 UTC, sakirma approved these changes

2020-12-07 15:27 UTC, martijnmelchers requested changes
Eigenlijk moet de XML branch er eerst in zodat je niet enorme problemen krijgt

2020-12-07 15:30 UTC, marc0tjevp commented
> Eigenlijk moet de XML branch er eerst in zodat je niet enorme problemen krijgt

Wat gaat er clashen? De kleine aanpassing aan main menu is verder niet related aan de functionaliteit. Dit terugmergen zou prima moeten kunnen denk ik.

2020-12-08 10:27 UTC, Ker0h approved these changes
Ziet er goed uit

2020-12-08 10:35 UTC, merged